### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by Xkeeper0** [FIX94/gameboy-audio-dumper#1]
For those of us who have actual flashcarts, can you provide a version that can just be flashed to a standalone cart for hotswapping instead of requiring a donor Yellow cart?

**Comment by mariomadproductions** [comment]
This could be a good idea, but can't you use the same hardware used to flash the flashcart to read a normal cart? Or are there GB/C flashcarts that work by plugging them into a PC / with removable storage (e.g. with an SD card)?

**Comment by Xkeeper0** [comment]
I have two flash carts; one is the Everdrive GB, which takes a SD card and transfers ROMs to its internal flash temporarily; the other one is the [gb smart card](http://store.kitsch-bent.com/product/usb-64m-smart-card), which connects over USB for reading/writing.

I can only read and write data on the actual flash carts with those, unfortunately; I can't read arbitrary cartridges.

In the worst case, I could flash a copy of Pokemon Yellow and the save file onto one of them, but it would be nice to skip the intermediary step. [swapdump](https://github.com/Sanqui/swapdump) is a similar hotswap tool for checking cartridge checksums, for example.

**Comment by FIX94** [comment]
I liked the idea so I just pushed a very basic version, it boots fine in the emus I tested and it duplicates itself just fine when I record my emulator audio so if you could see if this actually runs on a real gameboy color that would be cool.
[gb-audio-dumper.zip](https://github.com/FIX94/gameboy-audio-dumper/files/2565881/gb-audio-dumper.zip)

**Comment by FIX94** [comment]
Well if tested yet or not, I felt like doing a little cleaner job, so here is another standalone .gb rom file. If everything is alright with it I guess I would go ahead and make it a new overall release.
[gb-audio-dumper.zip](https://github.com/FIX94/gameboy-audio-dumper/files/2578257/gb-audio-dumper.zip)

**Comment by Xkeeper0** [comment]
I haven't had a chance to test it, but I'll give it a shot tonight if I can and let you know the results.

**Comment by FIX94** [comment]
well, I now just pushed a new version with the rom included as release so I'll close this for now, I'd still like to hear if it actually works at some point so feel free to reply in this or make a new issue in case something is wrong.
